apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-microservice-deployment
  namespace: prod
  labels:
    app: users-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-microservice
  template:
    metadata:
      labels:
        app: users-microservice
    spec:
      containers:
        - name: users-microservice
          image: microecommerceregistry.azurecr.io/users-microservice:__TAG__
          ports:
            - containerPort: 9090

          envFrom:
            - configMapRef:
                name: prod-config

          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production

            - name: ConnectionStrings__PostgresConnection
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: connectionString
