apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: uat
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: scottazurecontainerregistry.azurecr.io/ecommerce-postgres:latest
          envFrom:
            - configMapRef:
                name: dev-config
            - secretRef:
                name: postgres-credentials

          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_DB
          ports:
            - containerPort: 5432
