apiVersion: v1
kind: ConfigMap
metadata:
  name: uat-config
  namespace: uat
data:
  # PostgreSQL host, port, and database name (non-sensitive)
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: eCommerceUsers

  # Other service endpoints
  UsersMicroservicePort: "8080"
  UsersMicroserviceName: apigateway
  ProductsMicroservicePort: "8080"
  ProductsMicroserviceName: apigateway

  # Redis
  REDIS_HOST: redis
  REDIS_PORT: "6379"

  # RabbitMQ (non-sensitive bits)
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  RABBITMQ_PRODUCTS_EXCHANGE: products.exchange
  RABBITMQ_USERS_EXCHANGE: users.exchange
